import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import { Home, Video, ImageIcon, FileText } from "lucide-react";
import { FirebaseProvider } from "@/contexts/FirebaseContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check if Clerk keys are configured
  const hasClerkKeys = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY && 
                      process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY !== 'YOUR_PUBLISHABLE_KEY';

  if (!hasClerkKeys) {
    return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100 min-h-screen`}>
          <div className="min-h-screen flex items-center justify-center p-8">
            <div className="max-w-2xl mx-auto bg-white/80 backdrop-blur-sm rounded-2xl shadow-lg border border-gray-200 p-8 text-center">
              <div className="w-16 h-16 bg-gradient-to-r from-red-500 to-orange-500 rounded-full flex items-center justify-center mx-auto mb-6">
                <span className="text-white text-2xl font-bold">!</span>
              </div>
              <h1 className="text-3xl font-bold text-gray-900 mb-4">Clerk Configuration Required</h1>
              <p className="text-lg text-gray-600 mb-6">
                To use authentication features, you need to add your Clerk API keys to the environment variables.
              </p>
              <div className="bg-gray-50 rounded-lg p-4 mb-6 text-left">
                <h3 className="font-semibold text-gray-900 mb-2">Steps to fix:</h3>
                <ol className="list-decimal list-inside space-y-2 text-gray-700">
                  <li>Go to <a href="https://dashboard.clerk.com" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">Clerk Dashboard</a></li>
                  <li>Create a new application or select existing one</li>
                  <li>Go to API Keys page</li>
                  <li>Copy your Publishable Key and Secret Key</li>
                  <li>Create a <code className="bg-gray-200 px-1 rounded">.env.local</code> file in your project root</li>
                  <li>Add the keys as shown below</li>
                </ol>
              </div>
              <div className="bg-gray-900 text-green-400 rounded-lg p-4 text-left font-mono text-sm mb-6">
                <div className="text-gray-400 mb-2"># .env.local</div>
                <div>NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_your_key_here</div>
                <div>CLERK_SECRET_KEY=sk_test_your_secret_key_here</div>
              </div>
              <p className="text-sm text-gray-500">
                After adding the keys, restart your development server with <code className="bg-gray-200 px-1 rounded">npm run dev</code>
              </p>
            </div>
          </div>
        </body>
      </html>
    );
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100 min-h-screen`}
        >
          <header className="bg-white/80 backdrop-blur-md border-b border-gray-200/50 sticky top-0 z-50 shadow-sm">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center h-16">
                {/* Logo and Navigation */}
                <div className="flex items-center gap-8">
                  <Link href="/" className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                    ClerkApp
                  </Link>
                  
                  <nav className="hidden md:flex items-center gap-6">
                    <Link 
                      href="/" 
                      className="flex items-center gap-2 px-4 py-2 rounded-lg text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200"
                    >
                      <Home className="w-4 h-4" />
                      Home
                    </Link>
                    <Link 
                      href="/videos" 
                      className="flex items-center gap-2 px-4 py-2 rounded-lg text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200"
                    >
                      <Video className="w-4 h-4" />
                      Video & Browsing
                    </Link>
                    <Link 
                      href="/ai-generator" 
                      className="flex items-center gap-2 px-4 py-2 rounded-lg text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200"
                    >
                      <ImageIcon className="w-4 h-4" />
                      AI Image Generator
                    </Link>
                    <Link 
                      href="/notes" 
                      className="flex items-center gap-2 px-4 py-2 rounded-lg text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200"
                    >
                      <FileText className="w-4 h-4" />
                      Notes
                    </Link>
                  </nav>
                </div>

                {/* Authentication */}
                <div className="flex items-center gap-4">
                  <SignedOut>
                    <div className="flex gap-3">
                      <SignInButton>
                        <button className="px-4 py-2 text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium">
                          Sign In
                        </button>
                      </SignInButton>
                      <SignUpButton>
                        <button className="px-6 py-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg hover:from-blue-700 hover:to-purple-700 transition-all duration-200 font-medium shadow-sm">
                          Sign Up
                        </button>
                      </SignUpButton>
                    </div>
                  </SignedOut>
                  <SignedIn>
                    <UserButton 
                      appearance={{
                        elements: {
                          avatarBox: "w-10 h-10 rounded-full border-2 border-blue-200 hover:border-blue-300 transition-colors duration-200"
                        }
                      }}
                    />
                  </SignedIn>
                </div>
              </div>
            </div>
          </header>

          {/* Mobile Navigation */}
          <div className="md:hidden bg-white/80 backdrop-blur-md border-b border-gray-200/50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center gap-4 py-3 overflow-x-auto">
                <Link 
                  href="/" 
                  className="flex items-center gap-2 px-3 py-2 rounded-lg text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200 text-sm whitespace-nowrap"
                >
                  <Home className="w-4 h-4" />
                  Home
                </Link>
                <Link 
                  href="/videos" 
                  className="flex items-center gap-2 px-3 py-2 rounded-lg text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200 text-sm whitespace-nowrap"
                >
                  <Video className="w-4 h-4" />
                  Videos
                </Link>
                <Link 
                  href="/ai-generator" 
                  className="flex items-center gap-2 px-3 py-2 rounded-lg text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200 text-sm whitespace-nowrap"
                >
                  <ImageIcon className="w-4 h-4" />
                  AI Generator
                </Link>
                <Link 
                  href="/notes" 
                  className="flex items-center gap-2 px-3 py-2 rounded-lg text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200 text-sm whitespace-nowrap"
                >
                  <FileText className="w-4 h-4" />
                  Notes
                </Link>
              </div>
            </div>
          </div>

          <main>
            <FirebaseProvider>
              {children}
            </FirebaseProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
